namespace: "nutanix"
name: "nutanix"
version: "0.0.1-rc1"
readme: "README.md"
authors:
    - "Balu George (@balugeorge)"
    - "Sarath Kumar K (@kumarsarath588)"
license:
- GPL-2.0-or-later
tags: [nutanix, ahv]
repository: "https://www.github.com/ideadevice/ansible-ahv-provider-plugin"
